deploy:
  stage: deploy:uat
  variables:
    PROJECT_NAME: DMS-V2
    SERVICE_TYPE: dms-api-v2
    SERVICE_NAMESPACE: ${PROJECT_NAME}/${SERVICE_TYPE}
    ENABLED_BUILD: 'true'
    IP_ADDRESS: '109.123.237.239'
  environment:
    name: 'CamCyber/${PROJECT_NAME}/Development'
  only:
    # - /^v-.*-release$/
    - testing-executor
  before_script:
    - source "${CAMCYBER_UAT_ENVIRONMENT}"
  script:
    - echo $CI_COMMIT_REF_NAME
    - bash -e scripts/deploy.sh
