---
- name: Looking environments
  set_fact:
    project_name: "{{ lookup('env', 'PROJECT_NAME') | default('', true) }}"
    service_type: "{{ lookup('env', 'SERVICE_TYPE') | default('', true) }}"
    ci_project_path: "{{ lookup('env', 'CI_PROJECT_PATH') | default('', true) }}"
    ip_address: "{{ lookup('env', 'IP_ADDRESS') | default('', true) }}"

- name: Create app project directory
  ansible.builtin.file:
    path: /app/{{ project_name }}/{{ service_type }}/dist
    state: directory
    recurse: yes

- name: Sync dist directory to remote server
  shell: >
    rsync -avz -e"ssh -o StrictHostKeyChecking=no -i /builds/{{ ci_project_path }}/.ssh/id_rsa" --delete /builds/{{ ci_project_path }}/dist/ root@{{ ip_address }}:/app/{{ project_name }}/{{ service_type }}/dist/
  delegate_to: localhost

- name: Copy Nginx configuration to remote server
  shell: >
    rsync -avz -e"ssh -o StrictHostKeyChecking=no -i /builds/{{ ci_project_path }}/.ssh/id_rsa" /builds/{{ ci_project_path }}/default.conf root@{{ ip_address }}:/app/{{ project_name }}/{{ service_type }}/default.conf
  delegate_to: localhost

- name: Ensure Nginx Docker container is present
  docker_container:
    name: "{{ container_name }}"
    image: nginx:alpine
    state: started
    recreate: yes
    ports:
      - "{{ publish_port }}:{{ container_port }}"
    volumes:
      - /app/{{ project_name }}/{{ service_type }}/dist/:/usr/share/nginx/html
      - /app/{{ project_name }}/{{ service_type }}/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart_policy: unless-stopped
