- name: Looking environments
  set_fact:
    artifact_url: "{{ lookup('env', 'CI_PROJECT_URL') }}/-/jobs/{{ lookup('env', 'CI_JOB_ID') }}/artifacts/download"
    service_namespace: "{{ lookup('env', 'SERVICE_NAMESPACE') | default('', true) }}"
    project_name: "{{ lookup('env', 'PROJECT_NAME') | default('', true) }}"
    service_type: "{{ lookup('env', 'SERVICE_TYPE') | default('', true) }}"
    ci_project_path: "{{ lookup('env', 'CI_PROJECT_PATH') | default('', true) }}"
    ip_address: "{{ lookup('env', 'IP_ADDRESS') | default('', true) }}"

- name: Create app project directory
  ansible.builtin.file:
    path: /app/{{ project_name }}/{{ service_type }}/dist
    state: directory
    recurse: yes

- name: Sync dist directory to remote server
  shell: >
    rsync -avz -e"ssh -o StrictHostKeyChecking=no -i /builds/{{ ci_project_path }}/.ssh/id_rsa" --delete /builds/{{ ci_project_path }}/dist/ root@{{ ip_address }}:/app/{{ project_name }}/{{ service_type }}/dist/
  delegate_to: localhost

- name: Ensure Nginx Docker container is present
  docker_container:
    name: pms_web_dev
    image: nginx:latest
    state: started
    ports:
      - "2411:80"
    volumes:
      - /app/{{ project_name }}/{{ service_type }}/dist/:/usr/share/nginx/html
    restart_policy: unless-stopped
