name: CI/CD Pipeline & Notification

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Notify Telegram Push Event
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>${{ github.actor }}</b> pushed to branch <a href="${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }}">${{ github.ref_name }}</a> of ${{ github.event.repository.name }}
            📦 1 commit(s) — <a href="${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}">Compare changes</a>

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build API
        run: |
          cd api
          npm ci
          npm run build

      - name: Install & Build Web
        run: |
          cd web
          npm ci
          npm run build
        env:
          API_BASE_URL: "https://structure-project.onrender.com/api"
          FILE_BASE_URL: "https://file-v4-api.uat.camcyber.com"
          SOCKET_URL: "https://structure-project.onrender.com"
          GOOGLE_CLIENT_ID: "54356070191-kacqa35o9tefnughhdgi5b6jkhshso2c.apps.googleusercontent.com"

      - name: Notify Telegram on Success
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            ${{ github.event.repository.name }}: Pipeline <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">#${{ github.run_number }}</a> of branch <b>${{ github.ref_name }}</b> by ${{ github.actor }} has <b>passed</b>

      - name: Notify Telegram on Failure
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          disable_web_page_preview: true
          message: |
            ${{ github.event.repository.name }}: Pipeline <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">#${{ github.run_number }}</a> of branch <b>${{ github.ref_name }}</b> by ${{ github.actor }} has <b>failed</b>
